amazonclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('',include('shop.urls'),name="home"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop' 
urlpatterns = [
    path('',views.home, name='home'),
    path('productDetail/<slug:slug>', views.productDetail, name='productDetail'),
    # path('addToCart/<int:pk',views.addToCart, name='addToCart')

]

shop/models.py
from django.db import models

from django.template.defaultfilters import slugify


class Category(models.Model):
    name=models.CharField(max_length=100, unique=True)
    description=models.TextField()
   

    def __str__(self):
        return self.name
    
class Brand(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name
    
class ElectronicsBrand(Brand):
    pass
    

class ClotheBrand(Brand):
    pass


class HomeLivingBrand(Brand):
    pass

class BeautyPersonalCareBrand(Brand):
    pass

class SportsOutdoorsBrand(Brand):
    pass

class ToysGamesBrand(Brand):
    pass
class Colour(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name



class ProductImage(models.Model):
    image = models.ImageField(upload_to='additional_images/')

    def __str__(self):
        return self.image.url
    

class Product(models.Model):
    product_id=models.AutoField(primary_key=True,auto_created=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    colour = models.ForeignKey(Colour, on_delete=models.CASCADE, null=True, blank=True)
    slug = models.SlugField(null=True,blank=True, unique=True)
    main_image = models.ImageField(upload_to='product_images/', null=True, blank=True)
    additional_images = models.ManyToManyField('ProductImage', related_name='products')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.name)
        return super().save(*args, **kwargs)
    
class Electronics(Product):
    size_choices = (
        ('small', 'Small'),
        ('medium', 'Medium'),
        ('large', 'Large'),
    )
    size = models.CharField(max_length=10, choices=size_choices,default='small')
    subCategory_choices = (
        ('computer', 'Computer'),
        ('laptop', 'Laptop'),
        ('phone', 'Phone'),
        ('tablet', 'Tablet'),
        ('accessories', 'accessories'),
    )
    subCategory = models.CharField(max_length=50, choices=subCategory_choices,default='small')
    brand = models.ForeignKey(ElectronicsBrand, on_delete=models.CASCADE, null=True, blank=True)



class ComputerAndPhone(Electronics):
    screen_size = models.CharField(max_length=50)
    processor_type = models.CharField(max_length=100)
    storage_capacity = models.CharField(max_length=100)

class Accessories(Electronics):
    pass
  
class ClotheSize(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
class Clothe(Product):
    brand = models.ForeignKey(ClotheBrand, on_delete=models.CASCADE, null=True, blank=True)
    material = models.CharField(max_length=100)
    style = models.CharField(max_length=100)
    season = models.CharField(max_length=50)
    
    sizes = models.ManyToManyField(ClotheSize,blank=True)
    gender_choices = (
        ('men', 'Men'),
        ('women', 'Women'),
        ('kids', 'Kids'),
    )
    gender = models.CharField(max_length=10, choices=gender_choices, default='men')

   


class HomeLiving(Product):
    brand = models.ForeignKey(HomeLivingBrand, on_delete=models.CASCADE, null=True, blank=True)
    room_type = models.CharField(max_length=100)
    material = models.CharField(max_length=100)
    dimensions = models.CharField(max_length=100)


class BeautyPersonalCare(Product):
    brand = models.ForeignKey(BeautyPersonalCareBrand, on_delete=models.CASCADE, null=True, blank=True)
    SKIN_TYPES = [
        ('normal', 'Normal'),
        ('dry', 'Dry'),
        ('oily', 'Oily'),
        ('combination', 'Combination'),
        ('sensitive', 'Sensitive'),
    ]

    skin_type = models.CharField(max_length=20, choices=SKIN_TYPES, default='normal')
    fragrance_type = models.CharField(max_length=100)


class SportsOutdoors(Product):
    brand = models.ForeignKey(SportsOutdoorsBrand, on_delete=models.CASCADE, null=True, blank=True)
    sport_type = models.CharField(max_length=100)



class ToysGames(Product):
    brand = models.ForeignKey(SportsOutdoorsBrand, on_delete=models.CASCADE, null=True, blank=True)
    age_group = models.CharField(max_length=50)
    skill_level = models.CharField(max_length=50)


class TrendingProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

class MostSoldProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

# class Cart(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     created_at = models.DateTimeField(auto_now_add=True)

# class CartItem(models.Model):
#     cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     quantity = models.PositiveIntegerField(default=1)

#     def __str__(self):
#         return f"{self.product.name} - {self.quantity}"

shop/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse    
from django.template import loader
from .models import Product,Category,Clothe


# Create your views here.
def home(request):
    categories =Category.objects.all()
    category_products=[]
    for category in categories:
        products =Product.objects.filter(category=category)
        category_products.append({'category':category,'products':products})
    template= loader.get_template("main.html")

    return HttpResponse (template.render({'category_products':category_products},request))


def productDetail(request,slug):
    product = get_object_or_404(Product, slug=slug)
    template=loader.get_template("products/productDetail.html")

    return HttpResponse(template.render({'product':product},request))


# def addToCart(request,productId):
#     product = get_object_or_404(Product, id=productId)
#     # cart, created = Cart.objects.get_or_create(user=user)

#     if request.method=="POST":
#         selectedSize = None

#         if isinstance(product,Clothe):
#             selectedSize = request.POST.get('selectedSize')
        
#         cart =request.session.get('cart',{})
#         if productId in cart:
#             cart[productId]['quantity']+=1
        
#         else:
#             cart[productId]={'selectedSize':selectedSize,'quantity':1}

#         request.session['cart']= cart
    

#     return redirect('/')
    

shop/templates/products/productDetail.html
{% extends "base.html" %} 


{% block title %} Amazon {% endblock %} 
{% block content %}
{% include '../navbar/navbar.html' %}
{% include '../navbar/menuNavbar.html' %}
<main class="p-[10px]">

    
<section class="p-[10px] flex flex-col  gap-[20px] justify-around">
    {% comment %} {% if product.category.name == "Men" %} {% endcomment %}
    <h1 class="text-[30px]">{{product.name}}</h1>
    <hr>
    <div class="p-[10px] flex flex-wrap  gap-[20px] justify-around ">
        <div class="  items-center flex  justify-center">
            <div class="flex flex-col w-[50px] h-full gap-[10px] justify-center">
                {% for image in product.additional_images.all %}
                <img src="{{ image.image.url }}" class=" h-[50px] w-full " alt="{{ product.name }}"/>

                {% endfor %}
                
            </div>
            <img class="mb-[10px] object-cover mx-auto flex-1 "  src="{{ product.main_image.url }}" alt="{{ product.name }}" >
        </div>
        <div class="min-h-[300px] w-[40%] flex flex-col bg-white rounded shadow shadow-slate-600 p-[10px]">    
            <div class="p-5 flex flex-col justify-between flex-1 ">      
                    <h1 class="mb-[10px] font-bold text-[25px]">{{product.name}}</h1>
                    <p class="font-bold text-[30px]">${{product.price}}</p>
           
                <h3 class="mb-[10px] text-black">Category: {{product.category.name}}</h3>

                 <small class="mb-[5px] mb-[20px]">{{product.description}} </small> 
                <form method="POST" action ="{% url 'addToCart' product.id %}">
                    <div class="flex justify-between mb-[20px]">
                    {% if product.category.name == "Electronics" %}
                        <p>Size: {{ product.electronics.size }}</p>
                        <p>Brand: {{ product.electronics.brand.name }}</p>
                        <!-- Add other fields specific to Electronics -->
                    {% elif product.category.name == "Clothes" %}
                    <p>Size: </p>
                    <select class="w-[50%]" name="selectedSize">
                        {% for size in product.clothe.sizes.all %}
                                <option value="{{size.name}}">{{size.name}}</option>             
                                {% endfor %}
                            </select>
                        <!-- Add other fields specific to Clothes -->
                    {% elif product.category.name == "HomeLiving" %}
                        <p>Room Type: {{ product.homeliving.room_type }}</p>
                        <p>Brand: {{ product.homeliving.brand.name }}</p>
                        <!-- Add other fields specific to HomeLiving -->
                    {% elif product.category.name == "BeautyPersonalCare" %}
                        <p>Skin Type: {{ product.beautypersonalcare.skin_type }}</p>
                        <p>Brand: {{ product.beautypersonalcare.brand.name }}</p>
                        <!-- Add other fields specific to BeautyPersonalCare -->
                    {% elif product.category.name == "SportsOutdoors" %}
                        <p>Sport Type: {{ product.sportsoutdoors.sport_type }}</p>
                        <p>Brand: {{ product.sportsoutdoors.brand.name }}</p>
                        <!-- Add other fields specific to SportsOutdoors -->
                    {% elif product.category.name == "ToysGames" %}
                        <p>Age Group: {{ product.toysgames.age_group }}</p>
                        <p>Skill Level: {{ product.toysgames.skill_level }}</p>
                        <p>Brand: {{ product.toysgames.brand.name }}</p>
                        <!-- Add other fields specific to ToysGames -->
                    {% endif %}

                        </div>


                    <hr>
    
                
                    <p class="mb-[10px]">Total Quantity in Stock: {{product.quantity}}</p> 
                    <button type="submit" class="p-2 w-full bg-red-400 rounded text-white">Add to Cart </button>
                </form>
            </div>
        </div> 

        
      
    </div>
</section>
    {% comment %} {% endif %} {% endcomment %}

        </main>
 {% include 'footer/footer.html' %}
        
        
 {% endblock %}
   
  
   
    

shop/templates/products/productList.html
{% for category_product in category_products %}
<section class="p-[10px] flex flex-col  gap-[20px] justify-around">
    {% comment %} {% if product.category.name == "Men" %} {% endcomment %}
    <h1 class="text-[30px]">{{category_product.category.name}}</h1>
    <hr>
    <div class="p-[10px] flex flex-wrap  gap-[20px] justify-around">
    {% for product in category_product.products%}

        <div class="min-h-[300px] w-[400px] flex flex-col bg-white rounded shadow shadow-slate-600 p-[10px]">
            
            <img class="mb-[10px] object-cover mx-auto max-h-[200px]"  src="{{ product.main_image.url }}" alt="{{ product.name }}" >
            <div class="p-5 flex flex-col justify-between flex-1 ">
                <a  href="{% url 'shop:productDetail' product.slug %}">
                <div class="flex flex-row justify-between ">
            
                    <h1 class="mb-[10px] font-bold">{{product.name|truncatewords:5}}</h1>
                    <p>${{product.price}}</p>
                </div>
            </a>
                <h3 class="mb-[10px] text-black">Category: {{product.category.name}}</h3>

                {% comment %} <small class="mb-[5px]">{{product.description|truncatechars:40}} </small>
                <select class="mb-[10px]">
                    <option value ="small">SM</option>
                    <option value ="medium">M</option>
                    <option value ="large">L</option>
                    <option value ="extralarge">XL</option>


                </select> {% endcomment %}
                {% comment %} <p class="mb-[10px]">Total Quantity in Stock: {{product.quantity}}</p> {% endcomment %}
                <button class="p-2 w-full bg-red-400 rounded text-white">Add to Cart </button>

            </div>
        </div> 
        {% empty %}
            <p> No items avaiable </p>

   
        
        {% endfor %}
    </div>
</section>
    {% comment %} {% endif %} {% endcomment %}
    {% endfor %}
   
  
   
    