accounts/urls.py
from django.urls import path
from .views import SignUpView,LoginView,LogoutView,PasswordForgotView,PasswordResetView
from accounts.views import ProfileAccountView



app_name='accounts'
urlpatterns = [
  
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('passwordforgot/', PasswordForgotView.as_view(), name='passwordforgot'),
    path("password-reset/<email>/<token>/",PasswordResetView.as_view(), name="passwordreset"),
    path("profile-account",ProfileAccountView.as_view(), name="profile-account"),

]

amazonclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('',include('shop.urls'),name="home"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop' 
urlpatterns = [
    path('',views.home, name='home'),
    path('productDetail/<slug:slug>', views.productDetail, name='productDetail'),
    # path('addToCart/<int:pk',views.addToCart, name='addToCart')

]

shop/models.py
from django.db import models

from django.template.defaultfilters import slugify


class Category(models.Model):
    name=models.CharField(max_length=100, unique=True)
    description=models.TextField()
   

    def __str__(self):
        return self.name
    
class Brand(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name
    
class ElectronicsBrand(Brand):
    pass
    

class ClotheBrand(Brand):
    pass


class HomeLivingBrand(Brand):
    pass

class BeautyPersonalCareBrand(Brand):
    pass

class SportsOutdoorsBrand(Brand):
    pass

class ToysGamesBrand(Brand):
    pass
class Colour(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name



class ProductImage(models.Model):
    image = models.ImageField(upload_to='additional_images/')

    def __str__(self):
        return self.image.url
    

class Product(models.Model):
    product_id=models.AutoField(primary_key=True,auto_created=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    colour = models.ForeignKey(Colour, on_delete=models.CASCADE, null=True, blank=True)
    slug = models.SlugField(null=True,blank=True, unique=True)
    main_image = models.ImageField(upload_to='product_images/', null=True, blank=True)
    additional_images = models.ManyToManyField('ProductImage', related_name='products')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.name)
        return super().save(*args, **kwargs)
    
class Electronics(Product):
    size_choices = (
        ('small', 'Small'),
        ('medium', 'Medium'),
        ('large', 'Large'),
    )
    size = models.CharField(max_length=10, choices=size_choices,default='small')
    subCategory_choices = (
        ('computer', 'Computer'),
        ('laptop', 'Laptop'),
        ('phone', 'Phone'),
        ('tablet', 'Tablet'),
        ('accessories', 'accessories'),
    )
    subCategory = models.CharField(max_length=50, choices=subCategory_choices,default='small')
    brand = models.ForeignKey(ElectronicsBrand, on_delete=models.CASCADE, null=True, blank=True)



class ComputerAndPhone(Electronics):
    screen_size = models.CharField(max_length=50)
    processor_type = models.CharField(max_length=100)
    storage_capacity = models.CharField(max_length=100)

class Accessories(Electronics):
    pass
  
class ClotheSize(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
class Clothe(Product):
    brand = models.ForeignKey(ClotheBrand, on_delete=models.CASCADE, null=True, blank=True)
    material = models.CharField(max_length=100)
    style = models.CharField(max_length=100)
    season = models.CharField(max_length=50)
    
    sizes = models.ManyToManyField(ClotheSize,blank=True)
    gender_choices = (
        ('men', 'Men'),
        ('women', 'Women'),
        ('kids', 'Kids'),
    )
    gender = models.CharField(max_length=10, choices=gender_choices, default='men')

   


class HomeLiving(Product):
    brand = models.ForeignKey(HomeLivingBrand, on_delete=models.CASCADE, null=True, blank=True)
    room_type = models.CharField(max_length=100)
    material = models.CharField(max_length=100)
    dimensions = models.CharField(max_length=100)


class BeautyPersonalCare(Product):
    brand = models.ForeignKey(BeautyPersonalCareBrand, on_delete=models.CASCADE, null=True, blank=True)
    SKIN_TYPES = [
        ('normal', 'Normal'),
        ('dry', 'Dry'),
        ('oily', 'Oily'),
        ('combination', 'Combination'),
        ('sensitive', 'Sensitive'),
    ]

    skin_type = models.CharField(max_length=20, choices=SKIN_TYPES, default='normal')
    fragrance_type = models.CharField(max_length=100)


class SportsOutdoors(Product):
    brand = models.ForeignKey(SportsOutdoorsBrand, on_delete=models.CASCADE, null=True, blank=True)
    sport_type = models.CharField(max_length=100)



class ToysGames(Product):
    brand = models.ForeignKey(SportsOutdoorsBrand, on_delete=models.CASCADE, null=True, blank=True)
    age_group = models.CharField(max_length=50)
    skill_level = models.CharField(max_length=50)


class TrendingProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

class MostSoldProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

# class Cart(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     created_at = models.DateTimeField(auto_now_add=True)

# class CartItem(models.Model):
#     cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     quantity = models.PositiveIntegerField(default=1)

#     def __str__(self):
#         return f"{self.product.name} - {self.quantity}"

shop/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse    
from django.template import loader
from .models import Product,Category,Clothe


# Create your views here.
def home(request):
    categories =Category.objects.all()
    category_products=[]
    for category in categories:
        products =Product.objects.filter(category=category)
        category_products.append({'category':category,'products':products})
    template= loader.get_template("main.html")

    return HttpResponse (template.render({'category_products':category_products},request))


def productDetail(request,slug):
    product = get_object_or_404(Product, slug=slug)
    template=loader.get_template("products/productDetail.html")

    return HttpResponse(template.render({'product':product},request))


# def addToCart(request,productId):
#     product = get_object_or_404(Product, id=productId)
#     # cart, created = Cart.objects.get_or_create(user=user)

#     if request.method=="POST":
#         selectedSize = None

#         if isinstance(product,Clothe):
#             selectedSize = request.POST.get('selectedSize')
        
#         cart =request.session.get('cart',{})
#         if productId in cart:
#             cart[productId]['quantity']+=1
        
#         else:
#             cart[productId]={'selectedSize':selectedSize,'quantity':1}

#         request.session['cart']= cart
    

#     return redirect('/')
    

shop/templates/navbar/loginButton.html
{% load static %}
 <div class="relative group  flex flex-col justify-center items-center  px-[10px]  border border-transparent hover:border-white h-full">
    <div id="#openModal">
    <small class="text-[12px] text-gray-400 text-center items-center">Hello, {% if user.is_authenticated and not user.is_admin %}{{user.username}} {% else %} sign in{% endif %}</small>
    <p>Accounts & Lists  <i class=" fa-solid fa-caret-down  text-gray-300 "></i></p>
    </div>
    {% include 'navbar/loginModal.html' %}

 </div>

shop/templates/navbar/loginModal.html
<!-- Modal Container -->
<div id="myModal" class=" absolute  bg-white  shadow-2xl flex flex-col justify-center items-center  z-50 text-white text-xs rounded  top-[50px] -right-[100%] opacity-0 group-hover:opacity-100  transition-opacity duration-[1s]   min:h-[200px] min:w-[500px] ">
    <!-- Modal content -->
    <div class="relative p-5  rounded">
        <i class="absolute fa-solid fa-caret-up z-50 -top-[10px] right-[50%]  text-white text-[20px]"></i>
        {% if not user.is_authenticated and not user.is_admin %}
        <div class="flex flex-col gap-[5px] w-full justify-center items-center border-b border-gray-300 pb-[5px]">
            <a type="button" href="{% url 'accounts:login' %}" class="bg-yellow-600 hover:opacity-50 p-[5px] md:w-[50%] w-[90%] h-[40px] flex justify-center  items-center rounded text-[16px]">
            <p>Login </p>
            </a>
            <small class='text-black '>New Customer? <a href="{% url 'accounts:signup' %}" class="underline hover:text-yellow-600">Sign up </a></small>
        </div> 
        
            {% endif %}
        <div class="flex  p-[20px] text-black gap-[20px] ">
            <div class="list w-[200px] flex flex-col gap-[10px]">
                <h2 class="text-[20px]">Your List</h2>
                <ul class="flex flex-col gap-[7px]">
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Create your list</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Baby WishList</a></li>
                </ul>       
            </div>

            <div class="flex flex-col gap-[10px] accounts w-[200px] border-l border-gray-300 pl-[20px]">
                <h2 class="text-[20px]">Your Accounts</h2>
                <ul class="flex flex-col gap-[7px]">
                    <li><a class="hover:text-yellow-500 hover:underline" href="{% url 'accounts:profile-account' %}" >Your Account</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Orders</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Keep shopping for</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Recommendations</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Prime Membership</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Memberships and Subscriptions</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Subscribe and Save Items</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Seller Account</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Pets</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Manage Your Content and Devices</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Music</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your App & Devices</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Prime Video</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Amazon Drive</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Your Kindle Unlimited</a></li>
                    {% if user.is_authenticated and not user.is_admin %}
                    <hr>
                    <li><a class="hover:text-yellow-500 hover:underline" href="#" >Switch Accounts</a></li>
                    <li><a class="hover:text-yellow-500 hover:underline" href="{% url 'accounts:logout' %}" >Sign Out</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

   
  
</div>

shop/templates/navbar/menuNavbar.html
<nav class="menuNavbar flex justify-between bg-gray-800 text-white py-[10px] px-[20px] overflow-x-scroll">
<ul class="flex  list-none gap-[5px] ">
    {% if user.is_authenticated and not user.is_admin %}
    <li  class="group  relative  flex flex-col justify-center items-center   border border-transparent hover:border-white h-full px-[10px]">

        <i class="fa-solid fa-bars"></i>
        {% include 'navbar/profileModal.html' %}
    </li>
    {% endif %}
    <li class="mr-[8px]">All</li>
    <li class="mr-[8px]">Sell</li>
    <li class="mr-[8px]">Best Sellars</li>
    <li class="mr-[8px]">Today's Deal</li>
    <li class="mr-[8px]">Prime</li>
    <li class="mr-[8px]">New Releases</li>
    <li class="mr-[8px]">Music</li>

</ul>

<div class="hidden sm:block">
    <p>kindle unlimited Try Your first month free

</div>

</nav>

shop/templates/navbar/navbar.html
{% load static %}

<nav class="mainNavbar  flex justify-between bg-[#17212d] text-white py-[5px] px-[20px] h-[60px] items-center ">
    <a href="/">
    <div class="relative border border-transparent hover:border-white flex items-center h-full mr-[20px] px-[10px]">

    <h2 class=" text-[30px] ">amazon<span class="text-[12px]">.com.au<span></h2>
        <img class="absolute top-8 w-[70px]" src="{% static 'images/amazonLogo.png' %}" alt="logo">
    </div>
</a>
    <div class="flex flex-row gap-[10px] px-[10px] justify-center items-center mx-[20px] border border-transparent hover:border-white h-full">
        <i class="fa-solid fa-location-dot"></i>
        <div class ="flex flex-col">
        <small class="text-[12px] text-gray-400">Deliver to Brisbane 4000 QLD</small>
        <p>To change, sign in or enter postcode</p>
        </div>
         </div>
    <div class="searchForm  h-[40px] flex flex-1 justify-center items-center border  mr-[20px] rounded overflow-hidden">
        <select class="text-black  h-full border rounded-r-0 rounded-l-[5px]">
            {% for category_product in category_products %}
            <option>{{category_product.category.name}}</option>
           
            {% endfor %}

        </select>
        <input type="input" placeholder="Search..." class="p-[5px] h-full flex-1" />
        <button class="py-[5px] h-full px-[10px] bg-yellow-600 text-black"> <i class="fa-solid fa-magnifying-glass text-white"></i></button>
    </div>

    <div class="flex flex-col justify-center items-center  border border-transparent hover:border-white h-full px-[10px] ">
        <p>EN</p>
    </div>
    {% include 'navbar/loginButton.html' %}
     <div class="flex flex-col justify-center items-center  px-[10px]  border border-transparent hover:border-white h-full">
        <small class="text-[12px] text-gray-400">Returns</small>
        <p>& Orders</p>
     </div>
     <div class="flex flex-col justify-center items-center   border border-transparent hover:border-white h-full px-[10px]">

        <p><i class="fa-solid fa-cart-shopping fa-2x"></i></p>
    </div>

</nav>

shop/templates/navbar/profileModal.html
<!-- Modal Container -->
<div id="myModal" class=" fixed bg-white  shadow-2xl flex flex-col py-[10px]   z-50   s rounded  top-[70px] left-0   w-[300px] transition ease-in duration-800 group-hover:translate-x-0 -translate-x-full ">
    <!-- Modal content -->
    <i class="fa-solid fa-user-circle fa-3x text-black text-center"></i>
    {% if user.is_authenticated %}
    <p class="text-black text-[20px] font-bold text-center">{{user.username}}</p>
    {% endif %}
    <hr class="my-[10px]">
    <ul class="w-full flex flex-col text-black">
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white"><a href="{% url 'accounts:profile-account' %}"> My Account</a></li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white">Purchases</li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white">Saved</li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white">History </li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white">Orders </li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white">WatchLists </li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white">Messages </li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white">Notification </li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white">Payments </li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white">Help </li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white">Settings </li>
        <li class="py-[10px] px-[20px] hover:bg-blue-300 hover:text-white"><a href="{% url 'accounts:logout' %}">Logout  </a></li>

    <ul>

</div>