accounts/urls.py
from django.urls import path
from .views import SignUpView,LoginView,LogoutView,PasswordForgotView,PasswordResetView
from accounts.views import ProfileAccountView



app_name='accounts'
urlpatterns = [
  
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('passwordforgot/', PasswordForgotView.as_view(), name='passwordforgot'),
    path("password-reset/<email>/<token>/",PasswordResetView.as_view(), name="passwordreset"),
    path("profile-account",ProfileAccountView.as_view(), name="profile-account"),

]

amazonclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('',include('shop.urls'),name="home"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop' 
urlpatterns = [
    path('',views.home, name='home'),
    path('productDetail/<slug:slug>', views.productDetail, name='productDetail'),
    # path('addToCart/<int:pk',views.addToCart, name='addToCart')

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.utils.decorators import classonlymethod

# Create your models here.
class Admin(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    full_name=models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username
    

class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name= models.CharField(max_length=200)
    address= models.CharField(max_length=200,null=True,blank=True)
    mobile=models.CharField(max_length=10)
    joined_on= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} ({self.joined_on.strftime('%Y-%m-%d %H:%M:%S')})"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Customer
from django.forms import widgets


class CustomerRegistrationForm(forms.ModelForm):
    username= forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password= forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    email= forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control'}))

    class Meta:
        model=Customer
        fields=["username", "password", "email", "full_name","address","mobile"]
        widgets= {
            'full_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Full Name..'}),
            'address':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter address..'}),
            'mobile':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter mobile number..'}),
        }

    def clean_username(self):
        uname=self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError("Customer with this username  already exists.")
        return uname

    def clean_email(self):
        em=self.cleaned_data.get("email")
        if User.objects.filter(email=em).exists():
            raise forms.ValidationError("Customer with this email already exists.")
        return em
    


class CustomerLoginForm(forms.Form):
    username= forms.CharField(widget=widgets.TextInput(attrs={'class':'form-control','placeholder':'Enter the username...'}))
    password= forms.CharField(widget=widgets.PasswordInput(attrs={'class':'form-control','placeholder':'Enter the password...'}))

class PasswordForgotForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "class": "form-control",
        "placeholder": "Enter the email used in customer account..."
    }))

    def clean_email(self):
        e = self.cleaned_data.get("email")
        if Customer.objects.filter(user__email=e).exists():
            pass
        else:
            raise forms.ValidationError(
                "Customer with this account does not exists..")
        return e
    

class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Enter New Password',
    }), label="New Password")
    confirm_new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Confirm New Password',
    }), label="Confirm New Password")

    def clean_confirm_new_password(self):
        new_password = self.cleaned_data.get("new_password")
        confirm_new_password = self.cleaned_data.get("confirm_new_password")
        if new_password != confirm_new_password:
            raise forms.ValidationError(
                "New Passwords did not match!")
        return confirm_new_password

accounts/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy,reverse
from django.views import generic
# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView as AuthLoginView
from django.contrib.auth import login, logout,authenticate
from django.contrib.auth.models import User
from .forms import *
from .models import *
from .utils import password_reset_token
from django.conf import settings
from django.core.mail import send_mail

class SignUpView(generic.CreateView):
    template_name="accounts/signup.html"
    form_class=CustomerRegistrationForm
    success_url=reverse_lazy('shop:home')

    # def get_context_data(self,**kwargs):
    #     context=super().get_context_data(**kwargs)
    #     return context
    
    def form_valid(self,form):
        if form.is_valid():
            username= form.cleaned_data.get("username")
            password= form.cleaned_data.get("password")
            email =form.cleaned_data.get("email")
            user= User.objects.create_user(username,email,password)
            form.instance.user=user
            login(self.request,user)
            return super().form_valid(form)
        else:

            return self.render_to_response(self.get_context_data(form=form))
    
    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url
        

class LogoutView(generic.View):

    def get(self, request):
        logout(request)
        return render(request,template_name='accounts/logout.html')
    
class LoginView(generic.FormView):
    template_name="accounts/login.html"
    form_class=CustomerLoginForm
    success_url= reverse_lazy('shop:home')

    def form_valid(self, form):
        if form.is_valid():
            uname= form.cleaned_data.get("username")
            pword= form.cleaned_data['password'] 
            usr= authenticate(username=uname, password=pword) 

            if usr is not None and Customer.objects.filter(user=usr).exists():
                login(self.request,usr)

            else:
                return render(self.request, self.template_name,{'form':self.form_class, "error":"Invalid Credential"})


            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form)) 
    
    def get_success_url(self):
        if "next" in self.request.GET:
            next_url=self.request.GET.get("next")
            return next_url
        else:
            return self.success_url



class PasswordForgotView(generic.FormView):
    template_name = "accounts/forgotpassword.html"
    form_class = PasswordForgotForm
    success_url = "/accounts/passwordforgot/?m=s"

    def form_valid(self, form):
        if form.is_valid():

            # get email from user
            email = form.cleaned_data.get("email")
            # get current host ip/domain
            url = self.request.META['HTTP_HOST']
            # get customer and then user
            customer = Customer.objects.get(user__email=email)
            user = customer.user
            # send mail to the user with email
            text_content = 'Please Click the link below to reset your password. '
            html_content = url + "/accounts/password-reset/" + email +\
                "/" + password_reset_token.make_token(user)+ "/"
            send_mail(
                'Password Reset Link | Amazon Clone',
                text_content + html_content,
                settings.EMAIL_HOST_USER,
                [email],
                fail_silently=False,
            )
            return super().form_valid(form)
        
        else:

            return self.render_to_response(self.get_context_data(form=form))
    # def get_context_data(self,**kwargs):
    #     context= super().get_context_data(**kwargs)
    #     context['bcontact']=BusinessContact.objects.all().order_by("id")
    #     context['btime']=BusinessTime.objects.all().order_by("id")

    #     return context
    


class PasswordResetView(generic.FormView):
    template_name = "accounts/passwordreset.html"
    form_class = PasswordResetForm
    success_url = reverse_lazy('accounts:login')

    def dispatch(self, request, *args, **kwargs):
        email = self.kwargs.get("email")
        user = User.objects.get(email=email)
        token = self.kwargs.get("token")
        if user is not None and password_reset_token.check_token(user, token):
            pass
        else:
            return redirect(reverse("accounts:passworforgot") + "?m=e")

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        
        if form.is_valid():
            password = form.cleaned_data['new_password']
            email = self.kwargs.get("email")
            user = User.objects.get(email=email)
            user.set_password(password)
            user.save()
            return super().form_valid(form)
        else:
            # Form is not valid, handle the error
            return self.render_to_response(self.get_context_data(form=form))

    # def get_context_data(self,**kwargs):
    #     context= super().get_context_data(**kwargs)
    #     context['bcontact']=BusinessContact.objects.all().order_by("id")
    #     context['btime']=BusinessTime.objects.all().order_by("id")

    #     return context


class ProfileAccountView(generic.TemplateView):
    def get(self,request):
        return render(request,template_name='accounts/profile-account.html')
        
        

accounts/templates/accounts/forgotpassword.html
{% extends 'base.html' %}

{% block title %}Password Forgot {% endblock %}


{% block content %}
{% include 'navbar/navbar.html' %}
{% include 'navbar/menuNavbar.html' %}
<div class="flex justify-center items-center mt-[20px]">
  
        <div class="flex flex-col gap-[20px] w-[500px] shadow-2xl p-5 rounded border-t-[2px] border-yellow-600">
            <h2 class="text-center  text-warning text-[20px] text-yellow-600">
                Reset Your Password
                <hr class=" bg-gray-500  mt-[10px]">
            </h2>
            
            {% if request.GET.m == "s" %}
            <h3>Password reset link is sent to your email address. Please check your email immediately.</h3>
            {% else %}
            {% if request.GET.m == "e" %}
            <h4 class="text-danger">Something went wrong. Please enter your email again.</h4>
            {% endif %}
           
            <form action="" method="POST" class="p-5">
                {% csrf_token %}

                {% include 'accounts/form.html' %}

                <button class="bg-blue-300 p-[10px] text-white rounded float-right hover:bg-yellow-600 transition-all duration-[1s]" >Reset Password</button>
            </form>
            {% endif %}
        </div>
 
</div>


{% endblock %}

accounts/templates/accounts/form.html
{% for field in form %}
{% if field.errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-[5px] rounded relative mb-[10px]" role="alert">
  <p>{{field.errors}}</p>
</div>
{% endif %}
  <div style="margin-bottom: 20px;" >
    <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
      {{ field.label_tag }}
    </label>
    <input class="w-full border border-gray-400 outline-gray-500 p-[10px] rounded" id="{{ field.id_for_label }}" maxlength="30" name="{{ field.html_name }}" placeholder="Enter your {{  field.html_name }} ...." type="text" /> 

    {% if field.help_text %}
      <small class="border border-gray-300" style="color: grey;">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar/navbar.html' %}
{% include 'navbar/menuNavbar.html' %}
<div class="flex justify-center items-center w-full  ">
  <div class ="flex flex-col w-[500px]  shadow-2xl p-[30px] rounded mt-[20px] border-t-[3px] border-yellow-600">
  <h2 class="text-[30px] mb-[20px] text-center">Login</h2>
  <form method="post" class="" >
    {% csrf_token %}
    {% if error %}
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-[5px] rounded relative mb-[10px]" role="alert">
      <p>{{error}}</p>
  </div>
    {% endif %}
   {% include 'accounts/form.html' %}
    <button type="submit"  class="bg-yellow-600 p-[10px] w-[90px] h-[45px] rounded float-right text-white hover:opacity-50 transition-all duration-[1s]">Login</button>

  </form>
  <p>Forgot Password?
    <a class="text-blue-300 hover:text-yellow-600 transition-all duration-[0.5s]" href="{% url 'accounts:passwordforgot' %}">Reset </a>now.
</p>
  <p>Don't have an account? <a class="text-blue-300 underline hover:text-yellow-600 transition-all duration-[0.5s]" href="{% url 'accounts:signup' %}">Sign up</a></p>
</div>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar/navbar.html' %}
{% include 'navbar/menuNavbar.html' %}
<div class="flex w-full  justify-center items-center ">
  <div class="flex flex-col justify-center items-center p-5 shadow-2xl gap-[20px] w-[500px] mt-[20px] rounded border-t-[3px] border-yellow-600">
    <h2 class="text-center text-[30px] fond-bold">Logged Out</h2>
    <hr class="bg-gray-600">
    <p>You have been successfully logged out.</p>
    <a href="{% url 'accounts:login' %}" class="bg-yellow-600 hover:bg-yellow-500 p-[5px]  w-[120px] text-center text-white rounded transition-all duration-[1s]">Login Again</a>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/passwordreset.html
{% extends 'base.html' %}

{% block title %}Password Reset {% endblock %}

{% block content %}
{% include 'navbar/navbar.html' %}
{% include 'navbar/menuNavbar.html' %}
<div class=" flex justify-center items-center w-full">
    
        <div class="flex flex-col w-[90%]  md:w-[50%]   sm:p-[30px] p-[5px] shadow-2xl rounded mt-[20px] border-t-[3px] border-yellow-600">
            <h2 class="text-center text-[15px] sm:text-[30px]  my-5  font-bold text-yellow-600">Reset Your Password </h2>
            <hr class="my-[10px]">

            <form action="" method="POST" class="flex flex-col  w-full ">
               
                {% csrf_token %}
                {% include 'accounts/form.html' %}
              
                <button class="p-[10px] bg-blue-300 hover:bg-yellow-600 text-white rounded my-[20px] w-[180px] text-center transition-all duration-[1s] ml-auto" >Reset Your Password </button>
            </form>
        </div>
 
</div>

{% endblock %}

accounts/templates/accounts/profile-account.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar/navbar.html' %}
{% include 'navbar/menuNavbar.html' %}
<div class="flex w-full  justify-center items-center ">
  <div class="flex flex-col justify-center items-center md:w-[80%] w-[90%] p-5  gap-[20px] mt-[20px] rounded  ">
    <h2 class="text-center text-[30px] fond-bold">Your Account</h2>
    <div class=" p-[10px] flex justify-evenly flex-wrap gap-[20px]">
        <div class="flex items-center rounded p-[10px] w-[300px] gap-5 border border-gray-300 hover:bg-gray-100">
            <div class="flex justify-center items-center rounded-full bg-gray-300 p-[20px]">
            <i class="fa-solid fa-boxes-packing "></i>
            </div>
            <div class="flex flex-col">
                <h2 class="text-[18px]">Your Orders</h2>
                <p class="text-[14px]">Track,return, cancel and order, download invoice or buy again
            </div>
        </div>
        <div class="flex items-center rounded p-[10px] w-[300px] gap-5 border border-gray-300 hover:bg-gray-100">
            <div class="flex justify-center items-center rounded-full bg-gray-300 p-[20px]">
                <i class="fa-solid fa-shield-halved"></i>
            </div>
            <div class="flex flex-col">
                <h2 class="text-[18px]">Login & Security</h2>
                <p class="text-[14px]">Edit login, name and mobile number
            </div>
        </div>
        <div class="flex items-center rounded p-[10px] w-[300px] gap-5 border border-gray-300 hover:bg-gray-100">
            <div class="flex justify-center items-center rounded-full bg-gray-300 p-[20px]">
                <i class="fa-brands fa-amazon"></i>
            </div>
            <div class="flex flex-col">
                <h2 class="text-[18px]">Prime</h2>
                <p class="text-[14px]">Manage Membership, view benefits and payments settings
            </div>
        </div>
        <div class="flex items-center rounded p-[10px] w-[300px] gap-5 border border-gray-300 hover:bg-gray-100">
            <div class="flex justify-center items-center rounded-full bg-gray-300 p-[20px]">
                <i class="fa-solid fa-house-user"></i>
            </div>
            <div class="flex flex-col">
                <h2 class="text-[18px]">Your Addresses</h2>
                <p class="text-[14px]">Edit, remove or set default address</p>
            </div>
        </div>
        <div class="flex items-center rounded p-[10px] w-[300px] gap-5 border border-gray-300 hover:bg-gray-100">
            <div class="flex justify-center items-center rounded-full bg-gray-300 p-[20px]">
                <i class="fa-solid fa-credit-card"></i>

            </div>
            <div class="flex flex-col">
                <h2 class="text-[18px]">Payment</h2>
                <p class="text-[14px]">Manage, add payment method and view transactions</p>
            </div>
        </div>
        <div class="flex items-center rounded p-[10px] w-[300px] gap-5 border border-gray-300 hover:bg-gray-100">
            <div class="flex justify-center items-center rounded-full bg-gray-300 p-[20px]">
                <i class="fa-solid fa-gifts"></i>

            </div>
            <div class="flex flex-col">
                <h2 class="text-[18px]">Gift Cards</h2>
                <p class="text-[14px]">View balance or redeem a card, and purchase a new Gift Card</p>
            </div>
        </div>
        <div class="flex items-center rounded p-[10px] w-[300px] gap-5 border border-gray-300 hover:bg-gray-100">
            <div class="flex justify-center items-center rounded-full bg-gray-300 p-[20px]">
                <i class="fa-solid fa-headset"></i>

            </div>
            <div class="flex flex-col">
                <h2 class="text-[18px]">Customer Services</h2>
                <p class="text-[14px]">Browse self service options, help articles or contact us</p>
            </div>
        </div>
        <div class="flex items-center rounded p-[10px] w-[300px] gap-5 border border-gray-300 hover:bg-gray-100">
            <div class="flex justify-center items-center rounded-full bg-gray-300 p-[20px]">
                <i class="fa-solid fa-mobile-screen-button"></i>

            </div>
            <div class="flex flex-col">
                <h2 class="text-[18px]">Amazon Mobile Apps</h2>
                <p class="text-[14px]">Download amazon app</p>
            </div>
        </div>
        <div class="flex items-center rounded p-[10px] w-[300px] gap-5 border border-gray-300 hover:bg-gray-100">
            <div class="flex justify-center items-center rounded-full bg-gray-300 p-[20px]">
                <i class="fa-regular fa-envelope-open"></i>

            </div>
            <div class="flex flex-col">
                <h2 class="text-[18px]">Your Messages</h2>
                <p class="text-[14px]">View or respond to messages from Amazon, Sellers and Buyers</p>
            </div>
        </div>
        <div class="flex items-center rounded p-[10px] w-[300px] gap-5 border border-gray-300 hover:bg-gray-100">
            <div class="flex justify-center items-center rounded-full bg-gray-300 p-[20px]">
                <i class="fa-solid fa-suitcase-medical"></i>

            </div>
            <div class="flex flex-col">
                <h2 class="text-[18px]">Digital Services and Device Support</h2>
                <p class="text-[14px]">Troubleshoot device issues, manage or cancel digital subscriptions</p>
            </div>
        </div>
     
        
      
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar/navbar.html' %}
{% include 'navbar/menuNavbar.html' %}

<div class="flex justify-center items-center w-full  ">
  <div class ="flex flex-col w-[500px]  shadow-2xl p-[30px] m-[30px] rounded border-t-[3px] border-yellow-600">
  <h2 class="text-[30px] mb-[20px] text-center">Sign Up</h2>
  <form method="POST" class="" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
  
    {% for field in form %}
    {% if form.errors %}
 
    {% if field.errors %}
            <div class="bg-red-100 border border-red-400 text-red-700 p-[5px] rounded relative" role="alert">
                <strong class="font-bold">Error!</strong>
                <span class="block sm:inline">{{ field.label_tag }} {{ field.errors.0 }}</span>
            </div>
    {% endif %}
    
    {% if form.non_field_errors %}
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
            <strong class="font-bold">Error!</strong>
            <span class="block sm:inline">{{ form.non_field_errors.0 }}</span>
        </div>
    {% endif %}
    {% endif %}



      <div style="margin-bottom: 20px;" >
        <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
          {{ field.label_tag }}
        </label>
        <input class="w-full border border-gray-400 outline-gray-500 p-[10px] rounded" id="{{ field.id_for_label }}" maxlength="30" name="{{ field.html_name }}" placeholder="Enter your {{  field.html_name }} ...." type="text" /> 

        {% if field.help_text %}
          <small class="text-gray-300" >{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit"  class="bg-blue-300 p-[10px] w-[90px] h-[45px] rounded float-right text-white hover:bg-yellow-600 transition-all duration-[1s]">Sign Up</button>
  </form>
  <p>Have already account? <a class="text-blue-400 hover:text-yellow-600 underline transition-all duration-[1s]" href="{% url 'accounts:login' %}">Login</a></p>

</div>
</div>

{% endblock %}